version: '3.8'
services:
    mssql:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - '1433:1433'
        volumes:
            - sqldata:/var/opt/mssql
        image: mcr.microsoft.com/mssql/server
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
        container_name: sqlserver
    web-app:
        ports:
            - '80:80'
        container_name: webapp
        image: contactslibrarystilyan.azurecr.io/contacts
        restart: on-failure
        domainname: stilyan91
volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: stilyancontactsstorage

